#!/bin/bash

function md()
{
    mkdir $1 2> /dev/null
    if [ -d $1 ]
    then
        touch $1/README.md
    fi
}

function make_folders()
{
md rt
cd rt
>bobpath
while read a
do
    md $a
    echo $a >> bobpath
done << ___
img
map
obj
plate
prj
scene
studio
surf
tools
___

cd ..
}

function main()
{
    echo
    echo Creating Runtime Environment...
    make_folders
}

main "$@"

